### ISSUE TITLE
(sf)プロジェクト作成

### ISSUE THREAD

**Issue by ryokubozono** [QuickWorkInc/salesnow-salesforce#1]
前提
- salesnow-apiのアーキテクチャーを踏襲する。開発が進んだところでsalesnow-apiの認証基盤、DB（企業データベース）に乗っかりたい。
- docker, fastapi, postgresql
- コア機能の開発を優先する（接続テスト、SFからのフェッチ、SFに書き込み）
- 契約、ユーザー管理、apiキー取得機能は後から考える

このチケットのゴール
- スケルトンコードを作成してプッシュ。

**Comment by yhay81** [comment]
salesnow-apiにつくる
